---
title: "eds212-day5-comp"
author: "Joe DeCesaro"
date: "8/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Taking a look at `starwars`

-`include = `: show or hide everything
-`echo = `: show or hide code

```{r, echo=FALSE}
# summary of starwars
summary(starwars)

# Look at the first few lines
head(starwars)

# checkout dimensions
dim(starwars)

```

## Plot example and showing how to hide warnings
```{r, warning = FALSE}
ggplot(data = starwars, aes(x = height, y = mass)) +
  geom_point(color = "purple")
```

## Finding the mean, variance, and SD of character height
```{r}
sw_height_mean <- mean(starwars$height)
# the defaults of the `mean` function does not include missing values

sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_mean
# use the `na.rm = true`function to remove na's

# Using similar naming system, find:
# Variance of character height (var())
#Standard deviation of character height (sd())

sw_height_var <- var(starwars$height, na.rm = TRUE)
sw_height_var

sw_height_sd <- sd(starwars$height, na.rm = TRUE)
sw_height_sd

```

Mean character height is `r round(sw_height_mean, 1)` cm, with a standard deviation of `r round(sw_height_sd, 1)` cm.

## Logical expressions, rapid fire!
```{r}
5 < 10

"cat" > "armadillo"

"cat" > "elephant"

"dog" == "dog"
```

```{r}
10<=11

5>=4

3<=1

```

```{r}
tarantulas <- c(1, 3, 7, 10, 15)

tarantulas > 5
```

## Logical operators
- `!`
- `&`
- `|`

```{r}
3 < 1 | 8 > 2

6 < 10 & 5 < 1

7 != 11

4 != 4 | 2 < 5 | 6 > 10

0 == FALSE
1 == TRUE
# it is built in in programming languages for 0 to be false and 1 to be true

```

